-- Session-scoped inventory history: removing an item from an experiment
-- used to be a hard DELETE, so once removed there was no way to know it had
-- ever been reserved — reviewing a past session couldn't show what
-- equipment was actually in use during it. removeExperimentItem() switches
-- to a soft delete (status -> 'returned', returned_at = now()), and
-- getExperimentById() already returns every row regardless of status, so the
-- app can compute "items active during session N's time window" purely from
-- reserved_at/returned_at with no new query.
--
-- That requires loosening the existing full uniqueness on
-- (experiment_id, inventory_item_id): once a returned row is kept around as
-- history, re-adding the same item later would collide with it. The
-- constraint is looked up dynamically (rather than assumed by name) since
-- its autogenerated name isn't guaranteed.
do $$
declare
  v_constraint_name text;
begin
  select con.conname into v_constraint_name
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace ns on ns.oid = rel.relnamespace
  where ns.nspname = 'public'
    and rel.relname = 'experiment_items'
    and con.contype = 'u'
    and (
      select array_agg(attname::text order by attname)
      from unnest(con.conkey) as k(attnum)
      join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum
    ) = array['experiment_id', 'inventory_item_id'];

  if v_constraint_name is not null then
    execute format('alter table public.experiment_items drop constraint %I', v_constraint_name);
  end if;
end $$;

-- Only one *active* reservation of a given inventory item per experiment at
-- a time (the invariant the old constraint enforced); historical returned
-- rows for the same pair are now allowed to coexist.
create unique index if not exists experiment_items_active_unique
  on public.experiment_items(experiment_id, inventory_item_id)
  where status = 'active';

-- ---------------------------------------------------------------------------
-- Registration: separate "Nombres" / "Apellidos" fields instead of one free
-- text "Nombre completo". full_name is kept (still what most of the app
-- displays) and derived as first_name || ' ' || last_name at signup time.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column first_name text,
  add column last_name text;

-- Best-effort backfill for accounts that already exist: first token of
-- full_name -> first_name, the rest -> last_name. Approximate for
-- single-word names (last_name stays null) — acceptable for historical data,
-- new signups populate both properly.
update public.profiles
set
  first_name = split_part(full_name, ' ', 1),
  last_name = nullif(trim(substring(full_name from position(' ' in full_name))), '')
where full_name is not null;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, first_name, last_name)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;
